MyProject/MyProject/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aptcoder/',include("aptcoder.urls")),
]

MyProject/aptcoder/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views

app_name ="aptcoder"

urlpatterns = [
    path("",views.index,name="index"),
    path("login/",views.login_view,name="login"),
    path("logout/",views.logout_view,name="logout"),
    path("register_tech/",views.register_teach,name="register_teach"), 
    path("register_student/",views.register_student,name="register_student"), 
    path("<int:userid>/reg_course",views.reg_course,name="reg_course"),
    path("<int:userid>/reg_courseSt",views.reg_courseSt,name="reg_courseSt"),

]

MyProject/aptcoder/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class Teacher(models.Model):
	Tname = models.CharField(max_length=30)
	Tid = models.ForeignKey(User, on_delete=models.CASCADE, related_name="teacher")

	def __str__(self):
		return f"{self.id}: Teacher_name({self.Tname})"



class Student(models.Model):
	Sname = models.CharField(max_length=30)
	rolln = models.IntegerField()
	Sid = models.ForeignKey(User, on_delete=models.CASCADE, related_name="student")

	def __str__(self):
		return f"{self.id}: student_roll_number({self.rolln}) Student_name({self.Sname})"


		

class Course(models.Model):
	cname = models.CharField(max_length=30)
	cid = models.IntegerField()
	teacher = models.ManyToManyField(Teacher, blank=True, related_name="reg_course")
	student = models.ManyToManyField(Student, blank=True, related_name="reg_course")


	def __str__(self):
		return f"{self.id}: course_id({self.cid}) course_name({self.cname})"











MyProject/aptcoder/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *
# Create your views here.


class RegisterFormT(UserCreationForm):
    email = forms.EmailField()

    class Meta:
    	model = User
    	fields = ["username", "email", "password1", "password2"]


class RegisterFormS(UserCreationForm):
	email = forms.EmailField()
	rolln = forms.IntegerField(label="roll_number")

	class Meta:
		model = User
		fields = ["rolln","email","username","password1", "password2"]



def index(request):
	if not request.user.is_authenticated: 
		return render(request,"aptcoder/home.html")
	else:
		if request.user.teacher.all():
			h = request.user.teacher.get()
			student = []
			for c in Course.objects.filter(teacher=h):
				temp = []
				temp.append(c.cname)
				for s in c.student.all():
					temp.append(s.Sname)
				student.append(temp)
			return render(request, "aptcoder/user.html",{
				"student": student,
				"user":request.user,
				"name":h.Tname,
				"course":Course.objects.filter(teacher=h),
				"non_course": Course.objects.exclude(teacher=h).all()
				})
		elif request.user.student.all():
			h=request.user.student.get()

			teacher = []
			for c in Course.objects.filter(student=h):
				temp=[]
				temp.append(c.cname)
				for t in c.teacher.all():
					temp.append(t.Tname)
				teacher.append(temp)

			return render(request,"aptcoder/sdash.html",{
				"teacher":teacher,
				"user":request.user,
				"name":h.Sname,
				"course":Course.objects.filter(student=h),
				"non_course":Course.objects.exclude(student=h).all()
				})
			



def login_view(request):
	if request.method == "POST":
		username=request.POST["username"]
		password=request.POST["password"]
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return HttpResponseRedirect(reverse("aptcoder:index"))
		else:
			return render(request, "aptcoder/login.html",{
				"m": "Invalid"
				})
	return render(request,"aptcoder/login.html")

def logout_view(request):
	logout(request)
	return render(request, "aptcoder/login.html",{
				"m": "Logout"
				})


def register_teach(request):
	if request.method == "POST":
		form = RegisterFormT(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data["username"]
			tid=User.objects.get(username=username)
			teacher=Teacher(Tname=username,Tid=tid)
			teacher.save()
			return render(request, "aptcoder/login.html")
		else:
			return render(request, "aptcoder/register.html",{
				"form": form
				})

	return render(request, "aptcoder/register.html",{
				"form": RegisterFormT()
				})



	
def register_student(request):
	if request.method == "POST":
		form = RegisterFormS(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data["username"]
			rolln = form.cleaned_data["rolln"]
			sid=User.objects.get(username=username)
			student=Student(Sname=username,Sid=sid,rolln=rolln)
			student.save()
			return render(request, "aptcoder/login.html")
		else:
			return render(request, "aptcoder/reg_student.html",{
				"form": form
				})

	return render(request, "aptcoder/reg_student.html",{
				"form": RegisterFormS()
				})





def reg_course(request, userid):
	if request.method == "POST":
		teacher = Teacher.objects.get(Tid=userid)
		course = Course.objects.get(pk=int(request.POST["course"]))
		teacher.reg_course.add(course)

		student = []
		for c in Course.objects.filter(teacher=teacher):
			temp = []
			temp.append(c.cname)
			for s in c.student.all():
				temp.append(s.Sname)
			student.append(temp)

		return render(request, "aptcoder/user.html",{
					"student":student,
					"user":request.user,
					"name":teacher.Tname,
					"course":Course.objects.filter(teacher=teacher),
					"non_course": Course.objects.exclude(teacher=teacher).all(),
					})



def reg_courseSt(request, userid):
	if request.method == "POST":
		student = Student.objects.get(Sid=userid)
		course = Course.objects.get(pk=int(request.POST["course"]))
		student.reg_course.add(course)

		teacher = []
		for c in Course.objects.filter(student=student):
			temp=[]
			temp.append(c.cname)
			for t in c.teacher.all():
				temp.append(t.Tname)
			teacher.append(temp)

		return render(request, "aptcoder/sdash.html",{
					"teacher":teacher,
					"user":request.user,
					"name":student.Sname,
					"course":Course.objects.filter(student=student),
					"non_course": Course.objects.exclude(student=student).all(),
					})

MyProject/aptcoder/templates/aptcoder/home.html
{% extends "aptcoder/layout.html" %}

{% block body %}
<h1 style="text-align: center;color: blue;margin-top: 5%">WELCOME TO APTCODER</h1>
<div class="mydiv" style="width: 20%;margin-top:10%;margin-left: 38%">
	<ul>
		<li style="text-align: left">
			<b><h3><a href="{% url 'aptcoder:register_student' %}">REGISTERED AS STUDENT</a></h3></b>
		</li>
		<br>
		<li style="text-align: left">
			<b><h3><a href="{% url 'aptcoder:register_teach' %}">REGSITERED AS TEACHER </a></h3></b>
		</li>
		<br>
		<li style="text-align: left">
			<b><h3><a href="{% url 'aptcoder:login' %}">LOGIN</a></h3></b>
		</li>

	</ul>
</div>
{% endblock %}

MyProject/aptcoder/templates/aptcoder/layout.html
<!DOCTYPE html>
<html>
<head>
	<title>NewAptCoder.com</title>
	<style >
		.mydiv{
				border: 5px outset black;
				text-align:center;
				width: 450px;
				margin-left: 32%;
				margin-top: 10%;
				padding: 2%;
				border-radius: 20%;
			}
		.button{
			background-color: #4CAF50; /* Green */
				  color: white;
				  text-align: center;
				  display: inline-block;
				  font-size: 16px;
				  padding-left: 10px;
				  background-color: black;
				  border: 10px outset black;
				  border-radius: 20%;
		}
		.myself{
				border: 5px outset black;
				text-align:center;
				width: 300px;
				padding: 2%;
				border-radius: 20%;
			}
		.whole{
			border: 5px outset black;
			width: 1450px;
			height: 700px;
			padding-top:20px;
			padding-left: 20px;
			border-radius: 3%;
		}
	</style>
	<script>
		function validateForm() {
		  var x = document.forms["myForm"]["course"].value;
		  if (x == "" || x == null) {
		    alert("No courses are available");
		    return false;
		  }
		}
	</script>
</head>
<body style="background-color:LightGray">
	{% block body %}
	
	{% endblock %}

</body>
</html>

MyProject/aptcoder/templates/aptcoder/login.html
{% extends "aptcoder/layout.html" %}

{% block body %}

	<h3><a href="{% url 'aptcoder:index'%}">HOME</a></h3>
	<h1 style="text-align:center; margin-top:70px">LOGIN</h1>
	<form action="{% url 'aptcoder:login' %}" method="post">
		{% csrf_token %}
		<div class="mydiv"  style="margin-top: 100px">
		Username:<input type="text" name="username" placeholder="USERNAME" style="height: 30px"><br><br><br>
		Password:<input type="password" name="password" placeholder="PASSWORD" style="height: 30px"><br><br><br>
		<input type="submit" name="Login" class="button">
		</div>
	</form>
	{% if m %}
		<div style="text-align: center"><h3>{{ m }}</h3></div>
	{% endif %}
		
{% endblock %}

MyProject/aptcoder/templates/aptcoder/reg_student.html
{% extends "aptcoder/layout.html" %}


{% block body %}
<h3><a href="{% url 'aptcoder:index'%}">HOME</a></h3>
	<h1 style="text-align:center; margin-top:0%">Regsitration</h1>

	<form action="{% url 'aptcoder:register_student' %}" method="POST">
		{%  csrf_token %}
		<div class="mydiv">
			Email:{{form.email}}<br><br>
			Roll Number:{{form.rolln}}<br><br>
			Username:{{form.username}}<br><br>
			Password:{{form.password1}}<br><br>
			Confirm Password:{{form.password2}}<br><br>
		
		<input type="submit"  name="submit" align="center" class="button">
		</div>
	</form>
	<ul style="margin-left: 35%">
		<h3>Pasword should be:</h3>
		<li>150 characters or fewer. Letters, digits and @/./+/-/_ only.</li>
		<li>Your password can’t be too similar to your other personal information.</li>
		<li>Your password must contain at least 8 characters.</li>
		<li>Your password can’t be a commonly used password.</li>
		<li>Your password can’t be entirely numeric.</li>
	</ul>
{% endblock %}

MyProject/aptcoder/templates/aptcoder/register.html
{% extends "aptcoder/layout.html" %}

{% block body %}
<h3><a href="{% url 'aptcoder:index'%}">HOME</a></h3>
<h1 style="text-align:center; margin-top:0%">Registration</h1>
	<form action="{% url 'aptcoder:register_teach' %}" method="POST">
		{%  csrf_token %}
		<div class="mydiv">
			Email:{{form.email}}<br><br>
			Username: {{form.username}}<br><br>
			Password:{{form.password1}}<br><br>
			Confirm Password:{{form.password2}}<br><br>
		
		<input type="submit" name="submit" align="center" class="button">
		</div>
	</form>
	<ul style="margin-left: 35%">
		<h3>Pasword should be:</h3>
		<li>150 characters or fewer. Letters, digits and @/./+/-/_ only.</li>
		<li>Your password can’t be too similar to your other personal information.</li>
		<li>Your password must contain at least 8 characters.</li>
		<li>Your password can’t be a commonly used password.</li>
		<li>Your password can’t be entirely numeric.</li>
	</ul>
{% endblock %}

MyProject/aptcoder/templates/aptcoder/sdash.html
{% extends "aptcoder/layout.html" %}



{% block body %}
<div class="whole">
	<div class="myself" style="float:right;height: 85%;margin-right: 2%;width:40%">
		<h1 style="text-align: center">Course Discription</h1>
		<p>Context-free languages (CFLs) are generated by context-free grammars. The set of all context-free languages is identical to the set of languages accepted by pushdown automata, and the set of regular languages is a subset of context-free languages. An inputed language is accepted by a computational model if it runs through the model and ends in an accepting final state. All regular languages are context-free languages, but not all context-free languages are regular. Most arithmetic expressions are generated by context-free grammars, and are therefore, context-free languages. Context-free languages and context-free grammars have applications in computer science and linguistics such as natural language processing and computer language design.</p>
		<br><br>
		<p>All context-free languages are “pumpable” meaning that the pumping lemma constraints hold true for all context-free languages. If a language is not pumpable, then it is not a context-free language. However, if a language is pumpable, it is not necessarily a context-free language. Because the set of regular languages is contained in the set of context-free languages, all regular languages must be pumpable too.</p>
	</div>
	<div class="myself" style="float:right;height: 85%;margin-right: 2%;width:20%">
		<h1 style="text-align: center">Registered Teacher</h1>
		{% for teach in teacher%}
			<hr style="background-color: black">
			<o >Subject Name:</o>
			{% for thaught in teach%}
				<b>{{thaught}}</b>
				<br>
			{% endfor %}
			<hr style="background-color: black">
			<br>
		{% endfor %}
	</div>
	<div class="myself">
		<h1>Welcome, {{ name }}</h1>
		<ul style="text-align: left">
			<li>Username: {{ user.username }}</li>
			<li>Email: {{ user.email }}</li>
		</ul>
		<h3 style="text-align: left">Courses Opted</h3>
		<ul style="text-align: left">
			{% for course in course%}
				<li>{{course.cname}}:{{course.cid}}</li>
			{% endfor %}
		</ul>
	</div>
	<br>
	<div class="myself">
		<h2>Add Course</h2>
		<form name="myForm" onsubmit="return validateForm()" action="{% url 'aptcoder:reg_courseSt' user.id %}" method="post" required>
			{% csrf_token %}
			<select name="course" style="width: 50%">
				{% for course in non_course %}
					<option value="{{ course.id }}">{{ course.cname }}</option>
				{% endfor %}
				
			</select>
				<input type="submit" name="Submit" class="button">
		</form>
		<br><br>
	</div>
	<br><br>
	<h3>
		<a href="{% url 'aptcoder:logout' %}" style="margin-left: 10%">Log Out</a>
	</h3>
</div>
{% endblock %}

MyProject/aptcoder/templates/aptcoder/user.html
{% extends "aptcoder/layout.html" %}

{% block body %}
<div class="whole">
	<div class="myself" style="float:right;height: 85%;margin-right: 2%;width:40%">
		<h1 style="text-align: center">Course Discription</h1>
		<p>Context-free languages (CFLs) are generated by context-free grammars. The set of all context-free languages is identical to the set of languages accepted by pushdown automata, and the set of regular languages is a subset of context-free languages. An inputed language is accepted by a computational model if it runs through the model and ends in an accepting final state. All regular languages are context-free languages, but not all context-free languages are regular. Most arithmetic expressions are generated by context-free grammars, and are therefore, context-free languages. Context-free languages and context-free grammars have applications in computer science and linguistics such as natural language processing and computer language design.</p>
		<br><br>
		<p>All context-free languages are “pumpable” meaning that the pumping lemma constraints hold true for all context-free languages. If a language is not pumpable, then it is not a context-free language. However, if a language is pumpable, it is not necessarily a context-free language. Because the set of regular languages is contained in the set of context-free languages, all regular languages must be pumpable too.</p>
	</div>
	<div class="myself" style="float:right;height: 85%;margin-right: 2%;width:20%">
		<h1 style="text-align: center">Registered Student</h1>
		{% for st in student%}
			<hr style="background-color: black">
			<o >Subject Name:</o>
			{% for s in st%}
				<b>{{s}}</b>
				<br>
			{% endfor %}
			<hr style="background-color: black">
			<br>
		{% endfor %}
	</div>
	<div class="myself">
		<h1>Welcome, {{ name }}</h1>
		<ul style="text-align: left">
			<li>Username: {{ user.username }}</li>
			<li>Email: {{ user.email }}</li>

		</ul>
		<h3 style="text-align: left">Your Courses:</h3>
		<ul style="text-align: left">
			{% for course in course%}
				<li>{{course.cname}}:{{course.cid}}</li>
			{% endfor %}
		</ul>
	</div>
	<br>
	<div class="myself">
	<h2>Add Course</h2>
		<form name="myForm" onsubmit="return validateForm()" action="{% url 'aptcoder:reg_course' user.id %}" method="post" required>
			{% csrf_token %}
			<select name="course" style="width: 50%">
				{% for course in non_course %}
					<option value="{{ course.id }}">{{ course.cname }}</option>
				{% endfor %}
				
			</select>
				<input type="submit" name="Submit" class="button">
		</form>
	</div>
	<br><br>
	<h3>
		<a href="{% url 'aptcoder:logout' %}" style="margin-left: 10%">Log Out</a>
	</h3>
</div>
{% endblock %}